name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  shared_preferences: ^2.0.15
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/fonts/
    - assets/images/puzzle/
    - assets/images/find-the-plant/
    - assets/images/find-the-plant/background/
    - assets/images/find-the-plant/plant/
    - assets/images/backgrounds/
    - assets/json-files/
  fonts:
    - family: MonicaGarden
      fonts:
        - asset: assets/fonts/MonicaGarden.ttf
    - family: Billanta
      fonts:
        - asset: assets/fonts/Billanta.otf