name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backgrounds/puzzle-bg.jpg
    - assets/images/levels/level1-plant.jpg
    - assets/images/levels/level2-plant.jpg
    - assets/images/levels/level3-plant.jpg
    - assets/images/levels/level4-plant.jpg
    - assets/images/levels/level5-plant.jpg
    - assets/images/levels/level6-plant.jpg
    - assets/images/levels/level7-plant.jpg
    - assets/images/levels/level8-plant.jpg
    - assets/images/levels/level9-plant.jpg
    - assets/images/levels/level10-plant.jpg
    - assets/images/levels/level11-plant.jpg
    - assets/images/levels/level12-plant.jpg
    - assets/images/levels/level13-plant.jpg
    - assets/quiz-questions/quiz_questions.json
    - assets/images/find-the-plant/plant.png



